// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMobileHeader: typeof import('./src/components/app/AppMobileHeader.vue')['default']
    AppWebHeader: typeof import('./src/components/app/AppWebHeader.vue')['default']
    BaseTextInput: typeof import('./src/components/base/BaseTextInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
