// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMobileHeader: typeof import('./src/components/app/AppMobileHeader.vue')['default']
    AppWebHeader: typeof import('./src/components/app/AppWebHeader.vue')['default']
    BaseTextInput: typeof import('./src/components/base/BaseTextInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TournamentActions: typeof import('./src/components/tournament/TournamentActions.vue')['default']
    TournamentBaseLayout: typeof import('./src/components/layouts/TournamentBaseLayout.vue')['default']
    TournamentLayout: typeof import('./src/components/layouts/TournamentLayout.vue')['default']
    TournamentNavigation: typeof import('./src/components/tournament/TournamentNavigation.vue')['default']
    TournamentSettingsLayout: typeof import('./src/components/layouts/TournamentSettingsLayout.vue')['default']
    WhatComponent: typeof import('./src/components/layouts/WhatComponent.vue')['default']
  }
}
